import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import Navbar from "./components/Navbar";
import { auth } from "@/auth";
import { CartStoreProvider } from "@/store/CartProvider";

const poppins = Poppins({
	weight: ["300", "400", "700"],
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const session = await auth();
	return (
		<html lang="en" data-theme="light">
			<body className={`${poppins.className} container mx-auto`}>
				<CartStoreProvider>
					<Navbar user={session?.user!} />
					{children}
				</CartStoreProvider>
			</body>
		</html>
	);
}
